# Generated by Django 4.1.7 on 2023-04-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SkinDiseasesClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skin_image", models.ImageField(upload_to="skin_process/")),
                ("skin_classification", models.CharField(max_length=225)),
                ("skin_accuracy", models.CharField(max_length=225)),
            ],
            options={
                "verbose_name_plural": "Skin Diseases Classification",
            },
        ),
    ]
