# Generated by Django 4.1.7 on 2023-04-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkinDiseasesInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("definition", models.TextField()),
                ("causes", models.TextField()),
                ("treatment", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Skin Diseases Info",
            },
        ),
    ]
