# Generated by Django 4.1.7 on 2023-05-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0002_skindiseasesinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='skindiseasesclassification',
            name='skin_classification_ar',
            field=models.CharField(blank=True, max_length=225, verbose_name='skin Ar Classification'),
        ),
        migrations.AddField(
            model_name='skindiseasesinfo',
            name='causes_ar',
            field=models.TextField(blank=True, verbose_name='Ar causes'),
        ),
        migrations.AddField(
            model_name='skindiseasesinfo',
            name='definition_ar',
            field=models.TextField(blank=True, verbose_name='Ar definition'),
        ),
        migrations.AddField(
            model_name='skindiseasesinfo',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ar Title'),
        ),
        migrations.AddField(
            model_name='skindiseasesinfo',
            name='treatment_ar',
            field=models.TextField(blank=True, verbose_name='Ar treatment'),
        ),
        migrations.AlterField(
            model_name='skindiseasesclassification',
            name='skin_accuracy',
            field=models.CharField(max_length=225, verbose_name='skin_accuracy'),
        ),
        migrations.AlterField(
            model_name='skindiseasesclassification',
            name='skin_classification',
            field=models.CharField(max_length=225, verbose_name='skin En Classification'),
        ),
        migrations.AlterField(
            model_name='skindiseasesinfo',
            name='causes',
            field=models.TextField(verbose_name='En causes'),
        ),
        migrations.AlterField(
            model_name='skindiseasesinfo',
            name='definition',
            field=models.TextField(verbose_name='En definition'),
        ),
        migrations.AlterField(
            model_name='skindiseasesinfo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='En Title'),
        ),
        migrations.AlterField(
            model_name='skindiseasesinfo',
            name='treatment',
            field=models.TextField(verbose_name='En treatment'),
        ),
    ]
